{{- if not .Values.secrets.existingSecret }}
{{- $data := dict }}
{{- range $key, $value := .Values.secrets }}
{{- if and (ne $key "existingSecret") (ne (toString $value) "") }}
{{- if or (ne $key "WORKER_BROKER_URL") (not $.Values.redis.enabled) }}
{{- $_ := set $data $key (toString $value) }}
{{- end }}
{{- end }}
{{- end }}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "file-scanner.fullname" . }}
  labels:
    {{- include "file-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
