{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "file-scanner.fullname" . }}
  labels:
    {{- include "file-scanner.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "file-scanner.selectorLabels" (dict "root" . "component" "app") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- with .Values.metrics.serviceMonitor.bearerTokenSecret }}
      bearerTokenSecret:
        name: {{ . }}
        key: token
      {{- end }}
{{- end }}
